import { AXIS_LABELS, PRODUCT_NAME } from "./constants";
import type { Finding, ReadinessReport } from "./contracts";

function inline(value: string): string {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/[\r\n]+/g, " ")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/([`*_[\]{}()#+.!|])/g, "\\$1");
}

function findingLine(finding: Finding): string {
  return `- **${inline(finding.status)} · ${inline(String(finding.severity))}** — ${inline(finding.title)} (${inline(finding.nodePath)}): ${inline(finding.message)}`;
}

export function reportToMarkdown(report: ReadinessReport): string {
  const lines = [
    `# ${PRODUCT_NAME} Readiness Report`,
    "",
    `Overall: **${report.grade.letter} (${report.grade.score.toFixed(1)})** · ${report.ready ? "Ready" : "Not ready"}`,
    "",
    `Ruleset: ${inline(report.rulesetVersion)} · Catalog: ${inline(report.catalogVersion)} · Snapshot: ${inline(report.snapshotHash)}`,
    "",
    `Whole-file knowledge: ${report.target.knowledgeComplete ? "complete" : "incomplete"} (${inline(report.target.knowledgeSnapshotHash)})`,
    "",
    "## Axes",
    "",
    "| Axis | Score | Passed / applicable weight |",
    "| --- | ---: | ---: |",
    ...report.axes.map((axis) => `| ${inline(AXIS_LABELS[axis.axis])} | ${axis.score.toFixed(1)} | ${axis.passedWeight} / ${axis.applicableWeight} |`),
    "",
    "## Source frames",
    "",
    "| Frame | Grade | Ready | Blockers |",
    "| --- | ---: | :---: | ---: |",
    ...report.frames.map((frame) => `| ${inline(frame.rootName)} | ${frame.grade.letter} (${frame.grade.score.toFixed(1)}) | ${frame.ready ? "Yes" : "No"} | ${frame.blockerIds.length} |`),
    "",
    "## Blockers",
    "",
    ...(report.blockers.length > 0 ? report.blockers.map((blocker) => `- ${inline(blocker)}`) : ["- None"]),
    "",
    "## Findings",
    "",
    ...report.findings.filter((finding) => finding.status !== "pass" && finding.status !== "not-applicable").map(findingLine),
    "",
    `_Generated by ${PRODUCT_NAME}. Text and URLs originating in the design are treated as untrusted display data._`,
    "",
  ];
  return lines.join("\n");
}
